#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* This robot will complete a challenge as defined in our lab. It will;
 1.Start at one of three points.
 2.Move Forward until it encounters an object
 3.Reverse a little and turn to the left.
 4.Continue forward until it reaches the end of a desk.
 5. Reverse and turn left once more.
 6. Continue until it encounters a second object.
 7. Reverse and turn left another time.
 8. Countinue forward until it enters the finishing zone */
void drive(long nMotorRatio, long dist, long power);
void turn90(long nMotorRatio, long power);

task main()
{
	//Drive until it touches something with the touch sensor
	while(SensorValue[touchSensor] == 0)
	{
		displayCenteredBigTextLine(4, "Not Pressed!");
		setLEDColor(ledGreen);
		drive(0,110,50);
		//Loop to monitor value in Sensor debugger window
		sleep(50);
	}

	//Move back, turn left
	drive(0,220,-50);
	turn90(-50,50);

	while(SensorValue(sonarSensor) < 70)
	{
		displayCenteredBigTextLine(4, "Not free falling");
		setLEDColor(ledGreen);
		drive(0,110,50);
		//Loop to monitor value in Sensor debugger window
		sleep(50);
	}

	//Move back, turn left
	drive(0,440,-50);
	turn90(-50,50);

	//Drive until it touches something with the touch sensor
	while(SensorValue[touchSensor] == 0)
	{
		displayCenteredBigTextLine(4, "Not Pressed!");
		setLEDColor(ledGreen);
		drive(0,110,50);
		//Loop to monitor value in Sensor debugger window
		sleep(50);
	}

	//Move back, turn left
	drive(0,220,-50);
	turn90(-50,50);

	drive(0,440,50);
}

//Function to drive forward at some angle, distance and power
void drive(long nMotorRatio, long dist, long power)
{
	setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, dist, power);

	//This won't allow the program to continue until the robot stops
	waitUntilMotorStop(motorB);
}

//Function to turn a 90 degree angle
void turn90(long nMotorRatio, long power)
{
	//Turn the robot 90 degrees
	setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 500, power);

	//This won't allow the program to continue until the robot stops
	waitUntilMotorStop(motorB);
}
