#pragma config(Sensor, S1,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S2,     ColourSensor,   sensorEV3_Color)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int getTreshold();

task main()
{
	int threshold = getTreshold();
	/* Found by taking a reading on both DARK and LIGHT    */
	/* surfaces, adding them together, then dividing by 2. */

	//Keep looping forever
	while(true)
	{
		//If the color sensor senses the line (a dark value
		//lower than the calculated threshold of 50):
		if(getColorAmbient(S2) < threshold)
		{
			sleep(50);
		}

		//If the color sensor senses the surface(a light value
		//higher than the calculated threshold of 150):
		else
		{
	   setMotorSyncEncoder(leftMotor, rightMotor, 0, 500, 50);
		}
	}
}

//Function to ask user to set a high brightness level and a low brightness level, calculating the treshold by getting the average of both
int getTreshold()
{
	int lowBright = 0;
	int highBright = 0;
	int threshold = 0;

	while(!getButtonPress(buttonEnter))
	{

	displayCenteredBigTextLine(4, "Press enter - low");
	lowBright = SensorValue[S2];
	displayCenteredBigTextLine(4, "Low Reading: %d", lowBright);

	}

	while(getButtonpress(buttonEnter));

	while(!getButtonPress(buttonEnter))
	{

		displayCenteredBigTextLine(4, "Press enter - high");
		highBright = SensorValue[S2];
		displayCenteredBigTextLine(4, "High Reading: %d", highBright);
	}

	while(getButtonPress(buttonEnter));

	while(!getButtonPress(buttonEnter))
	{
		threshold = (highBright + lowBright) / 2;
		//Display both readings
		displayCenteredBigTextLine(4, "Threshold = %d",threshold);
	}
	return(treshold);
}
