#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void turn90degreesLeft(long time, long motorpower)
{
	setMotorSpeed(leftMotor, motorpower);			//Set the leftMotor to  power forward
	setMotorSpeed(rightMotor, -motorpower); 	//Set the rightMotor to  power reverse
	sleep(time);															//Wait before continuing on in the program

}

void turn90degreesRight(long time, long motorpower)
{
	setMotorSpeed(leftMotor, -motorpower);  //Set the leftMotor to  power reverse
	setMotorSpeed(rightMotor, motorpower);	//Set the rightMotor to  power forward
	sleep(time);														//Wait before continuing on in the program
}

void goForward1second(long motorpower)
{
	setMotorSpeed(leftMotor, motorpower);	 //Set the leftMotor to  power forward
	setMotorSpeed(rightMotor, motorpower); //Set the rightMotor to  power forward
	sleep(1000);													 //Wait 1 second before continuing on in the program
}

void swingRight90degrees(long motorpower)
{
	int i = 0;

	for(i=0;i<90;i=i+10)
	{
		setMotorSpeed(leftMotor, motorpower);			//Set the leftMotor (motor1) to half power forward (50)
		setMotorSpeed(rightMotor, -motorpower); 	//Set the rightMotor (motor6) to half power reverse (-50)
		sleep((3000/90)*i);												//turn a certain amount of degrees (increments of 9)

		setMotorSpeed(leftMotor, motorpower);			//Set the leftMotor (motor1) to half power forward (50)
		setMotorSpeed(rightMotor, motorpower);		//Set the rightMotor (motor6) to half power forward (50)
		sleep(200);																//Wait for 0.2 seconds before continuing on in the program.
	}


}

void swingLeft90degrees(long motorpower)
{
	int i = 0;

	for(i=0;i<90;i=i+10)
	{
		setMotorSpeed(leftMotor, -motorpower);	//Set the leftMotor (motor1) to half power forward (50)
		setMotorSpeed(rightMotor, motorpower); 	//Set the rightMotor (motor6) to half power reverse (-50)
		sleep((3000/90)*i);											//turn a certain amount of degrees (increments of 9)

		setMotorSpeed(leftMotor, motorpower);	 //Set the leftMotor (motor1) to half power forward (50)
		setMotorSpeed(rightMotor, motorpower); //Set the rightMotor (motor6) to half power forward (50)
		sleep(200);														 //Wait for 0.2 seconds before continuing on in the program.
	}

}

void reverse1second(long motorpower)
{
	setMotorSpeed(leftMotor, -motorpower);  //Set the leftMotor to  power reverse
	setMotorSpeed(rightMotor, -motorpower); //Set the rightMotor to  power reverse
	sleep(1000);														//Wait 1 second before continuing on in the program
}

task main()
{
	turn90degreesLeft(1500,50);

	turn90degreesRight(1500,50);

	goForward1second(50);

	swingRight90degrees(50);

	swingLeft90degrees(50);

	reverse1second(50);
}
