#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will move your robot forward for 2 seconds. At the end of the program, all motors
  will shut down automatically and turn off.

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    MotorC        			leftMotor           LEGO EV3 Motor		      Left side motor
    MotorB       				rightMotor          LEGO EV3 Motor		      Right side motor (reversed)
------------------------------------------------------------------------------------------------*/
//
// Test program as part of LAB2
//
void turnLeft(long time, long motorpower)
{

    setMotorSpeed(leftMotor, -motorpower);  //Set the leftMotor (motor1) to half power (50)
    setMotorSpeed(rightMotor, motorpower);  //Set the rightMotor (motor6) to half power (50)
    sleep(time);  //Wait for 2 seconds before continuing on in the program.
}
task main()
{
    turnLeft(1000,50);

}
