#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void moveRobot(long nMotorRatio, long time, long power) //Movement with PID functionality
{
	setMotorSyncTime(leftMotor, rightMotor, nMotorRatio, time, power);
	sleep(1500);
}

task main()
{
	int directionRandom;

	directionRandom = random(1);
	if (directionRandom==1)//if direction is equal 1 then it will make right turn square
	{
		moveRobot(0, 1000, 50);
		moveRobot(50, 1000, 50);// once it has turned right it will commit to making a square
		moveRobot(0, 1000, 50);
		moveRobot(50, 1000, 50);
		moveRobot(0, 1000, 50);
		moveRobot(50, 1000, 50);
		moveRobot(0, 1000, 50);
	}
	else // if direction is  0 then it will make a left turn square
	{
		moveRobot(0, 1000, 50);
		moveRobot(-50, 1000, 50); // once it has turned left it will commit to making a square
		moveRobot(0, 1000, 50);
		moveRobot(-50, 1000, 50);
		moveRobot(0, 1000, 50);
		moveRobot(-50, 1000, 50);
		moveRobot(0, 1000, 50);
	}

	moveRobot(0, 5000, 100); //This will make it go full power foward for 5 seconds
	moveRobot(50, 1000, 100); //This will make the robot turn 180 degrees
	moveRobot(0, 10000, 50); //This will mak the robot go half power foward for 10 seconds
}
